#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.valkyrie" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.valkyrie"
fi

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/philip/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/philip/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/philip/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/philip/google-cloud-sdk/completion.zsh.inc'; fi
