#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Add our customization
if [[ -s ~/.zshrc.valkyrie ]]; then
    source ~/.zshrc.valkyrie
fi

# Please the loaded modules in `zpreztorc`
# zstyle ':prezto:load' pmodule \
#   'git' \
#   'environment' \
#   'terminal' \
#   'editor' \
#   'history' \
#   'directory' \
#   'spectrum' \
#   'utility' \
#   'completion' \
#   'prompt'

autoload -U +X bashcompinit && bashcompinit
